config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :groups do 
    resources :messages 
  end 
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users  
  has_many :users ,through: :group_users  
  has_many :messages

  validates :name, presence: true

  accepts_nested_attributes_for :group_users

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group  
  belongs_to :user  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :text, :user_id, :group_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_many :group_users  
 has_many :groups , through: :group_users  
 has_many :messages  
 accepts_nested_attributes_for :group_users

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
    def after_sign_out_path_for(resource)
    '/users/sign_in'
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
   before_action :move_to_index, except: :index

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      flash.now[:alert] = "グループ名を入力してください"
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end
  
  def update
    group = Group.find(params[:id])
    group.update(group_params)
    redirect_to root_path
  end
  private

   def group_params
     params.require(:group).permit(:name, user_ids: [])
   end

   def move_to_index
     redirect_to action: :index unless user_signed_in?
   end
end

app/controllers/messages_controller.rb
  class MessagesController < ApplicationController
    before_action :often_time_used


  def index
    @message = Message.new
    @messages = @group.messages
  end

  def new
  end

  def create
    @message = current_user.messages.new(message_params)
     if @message.save
       redirect_to group_messages_url(@group)
     else
       redirect_to group_messages_url(@group), alert: '送信したいメッセージがありません。'
     end
  end


  def edit
    @group = Group.find(params[:id])
  end

  private

  def message_params
    params.require(:message).permit(:text).merge(group_id: params[:group_id])
  end

  def often_time_used
    @group = Group.find(params[:group_id])
    @groups = current_user.groups
    @users = @group.users
    @message = Message.new
    @messages = @group.messages
  end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name,"グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder:"グループ名を入力してください", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :test, "チャットメンバーを追加", class: "chat-group-form__label"
      .check_box
        = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b|
          = b.label {b.check_box + b.text}
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          = f.text_field :name, placeholder:"追加したいユーザを入力してください", class: "chat-group-form__input"
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        =f.label :name, "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", name: "commit", type: "submit", class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
%html
%body
  #header

  #container
    #side-content
      .user-info
        .User-info__name 
          %span 
            = current_user.name
        = link_to edit_user_registration_path do
          %i.fa.fa-cog
        = link_to new_group_path do
          %i.fa.fa-pencil-square-o
      %ul.groups
        - @groups.each do |group|
          = link_to group_messages_path(group.id) do
            %li.group
              .group__name 
                = group.name
              .group__last__massage まだメッセージはありません

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder:"グループ名を入力してください", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :test, "チャットメンバーを追加", class: "chat-group-form__label"
      .check_box
        = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b|
          = b.label {b.check_box + b.text}
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :test, "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          #chat-group-user-22.chat-group-user.clearfix
            %p.chat-group-user__name 
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", name: "commit", type: "submit", class: "chat-group-form__action-btn"
       

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/_message.html.haml
%li.message
  .message-info
    .message-info__owner 
      = message.user.name
    .message-info__updated-time 
      = message.created_at
  .message-content
    = message.text

app/views/messages/index.html.haml
!!!
%html
%body
  #header

  #container
    #side-content
      .user-info
        .User-info__name
          %span 
            = current_user.name
        = link_to edit_user_registration_path do
          %i.fa.fa-cog
        = link_to new_group_path do
          %i.fa.fa-pencil-square-o
      %ul.groups
        - @groups.each do |group|
          = link_to group_messages_path(group.id) do
            %li.group
              .group__name 
                = group.name
              .group__last__massage まだメッセージはありません

    #main-content
      .selected-group
        .selected-group__name 
          = @group.name
        .selected-group__members 
          Members : 
          - @users.each do |user|
            = user.name
        .selected-group__edit-box 
          = link_to edit_group_path(@group) do
            .selected-group__edit-box__text Edit
      .message-area
        %ul.messages
          = render partial: 'message', collection: @messages, as: 'message'
      .message-input
        = form_for [@group, @message] do |f|
          .message-input_area 
            = f.text_area :text, placeholder:"type a message"
          %i.fa.fa-picture-o.fa-lg{aria: {hidden: true}}
          = f.submit "Send", class: "send-box"
  %footer